jobs:
  include:
    - stage: build backend
      install:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      script:
        - mvn deploy
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: fhv-backend-staging
        api_key: $HEROKU_API_KEY
    - stage: automatic user acceptance tests on staging
      script:
        - cd ..
        - "git clone https://github.com/fhv-msi/sentiment-analysis-tests.git"
        - cd sentiment-analysis-tests
        - mvn verify
        - "cd ../sentiment-analysis-backend"
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: fhv-backend
    - stage: check production availability
      script: 'curl https://fhv-backend.herokuapp.com/'
